/**
 * Wire contract for the KQode backend message protocol.
 *
 * This module is a dependency-free seam shared by the `@state` and `@backend`
 * layers: it must not import from either side (or pull in transport libraries
 * such as `vscode-jsonrpc`) so it can never participate in a layer cycle.
 */

/**
 * KQode-owned JSON-RPC method that acknowledges a submitted prompt.
 *
 * Must match `RpcMethod::MessageSubmit` (via `RpcMethod::as_str`) in
 * `src/protocol.rs`.
 */
export const MESSAGE_SUBMIT_METHOD = 'kqode.message.submit';

/** Must match `RpcMethod::ConversationClear` (via `RpcMethod::as_str`) in `src/protocol.rs`. */
export const CONVERSATION_CLEAR_METHOD = 'kqode.conversation.clear';

/** Must match `RpcMethod::TurnCancel` (via `RpcMethod::as_str`) in `src/protocol.rs`. */
export const TURN_CANCEL_METHOD = 'kqode.turn.cancel';

/**
 * KQode-owned JSON-RPC method returning the workspace git status label.
 *
 * Must match `RpcMethod::GitStatus` (via `RpcMethod::as_str`) in
 * `src/protocol.rs`. The backend runs `git` in the workspace and formats the
 * label; the TUI renders the returned string verbatim.
 */
export const GIT_STATUS_METHOD = 'kqode.git.status';

/**
 * JSON-RPC notification the backend emits exactly once, as soon as it is
 * listening and speaking JSON-RPC and before it handles any request.
 *
 * Must match the `BACKEND_READY_METHOD` constant in `src/protocol.rs`. The TUI
 * bounds startup readiness on this notification instead of the OS process-spawn
 * event, so a backend that spawns but never speaks is caught by the startup
 * timeout.
 */
export const BACKEND_READY_METHOD = 'kqode.backend.ready';

/**
 * Payload for {@link BACKEND_READY_METHOD}: the backend-minted session id for
 * this spawn. Must match `BackendReadyParams` in `src/protocol.rs`.
 */
export type BackendReadyParams = {
  sessionId: string;
};

/**
 * Server→client notification carrying one chunk of streamed assistant text.
 * Must match `TOKEN_DELTA_METHOD` in `src/protocol.rs`.
 */
export const TOKEN_DELTA_METHOD = 'kqode/tokenDelta';

/**
 * Server→client notification marking the natural end of a streamed turn.
 * Must match `TURN_END_METHOD` in `src/protocol.rs`.
 */
export const TURN_END_METHOD = 'kqode/turnEnd';

/**
 * Server→client notification for a turn that ended with a provider error.
 * Must match `TURN_ERROR_METHOD` in `src/protocol.rs`.
 */
export const TURN_ERROR_METHOD = 'kqode/turnError';

/** Must match `TURN_ENQUEUED_METHOD` in `src/protocol.rs`. */
export const TURN_ENQUEUED_METHOD = 'kqode/turnEnqueued';

/** Must match `TURN_ACTIVATED_METHOD` in `src/protocol.rs`. */
export const TURN_ACTIVATED_METHOD = 'kqode/turnActivated';

/** Must match `TURN_SETTLED_METHOD` in `src/protocol.rs`. */
export const TURN_SETTLED_METHOD = 'kqode/turnSettled';

/** Must match `TURN_STATE_ACTIVE` in `src/protocol.rs`. */
export const TURN_STATE_ACTIVE = 'active';

/** Must match `TURN_STATE_PENDING` in `src/protocol.rs`. */
export const TURN_STATE_PENDING = 'pending';

/** Must match `SETTLED_KIND_COMPLETED` in `src/protocol.rs`. */
export const SETTLED_KIND_COMPLETED = 'completed';

/** Must match `SETTLED_KIND_NEEDS_CONFIGURATION` in `src/protocol.rs`. */
export const SETTLED_KIND_NEEDS_CONFIGURATION = 'needsConfiguration';

/** Must match `SETTLED_KIND_ERROR` in `src/protocol.rs`. */
export const SETTLED_KIND_ERROR = 'error';

/** Must match `SETTLED_KIND_CANCELLED` in `src/protocol.rs`. */
export const SETTLED_KIND_CANCELLED = 'cancelled';

/** `status` value when a submit is accepted and streaming has begun. */
export const SUBMIT_STATUS_STREAMING = 'streaming';

/** `status` value when a submit cannot run because no API key is configured. */
export const SUBMIT_STATUS_NEEDS_CONFIGURATION = 'needsConfiguration';

/**
 * Params for `kqode.message.submit`.
 *
 * `turnId` is generated by the client so it can register notification handlers
 * before sending, correlating streamed events without depending on ack ordering.
 * The Rust backend deserializes this with `#[serde(deny_unknown_fields)]`
 * (`MessageSubmitParams` in `src/protocol.rs`), so keep the two shapes in
 * lockstep.
 */
export type MessageSubmitParams = {
  text: string;
  turnId: string;
};

/**
 * Result for `kqode.message.submit`: an immediate streaming ack. `status` is one
 * of {@link SUBMIT_STATUS_STREAMING} or {@link SUBMIT_STATUS_NEEDS_CONFIGURATION}.
 */
export type MessageSubmitResult = {
  turnId: string;
  status: string;
};

/** Must match `ConversationClearParams` in `src/protocol.rs`. */
export type ConversationClearParams = Record<string, never>;

/** Must match `ConversationClearResult` in `src/protocol.rs`. */
export type ConversationClearResult = {
  ok: boolean;
};

/** Must match `TurnCancelParams` in `src/protocol.rs`. */
export type TurnCancelParams = {
  turnId: string;
};

/** Must match `TurnCancelResult` in `src/protocol.rs`. */
export type TurnCancelResult = {
  ok: boolean;
};

/** Payload for {@link TOKEN_DELTA_METHOD}. */
export type TokenDeltaParams = {
  turnId: string;
  delta: string;
};

/** Payload for {@link TURN_END_METHOD}. */
export type TurnEndParams = {
  turnId: string;
  finishReason: string | null;
};

/** Payload for {@link TURN_ERROR_METHOD}. */
export type TurnErrorParams = {
  turnId: string;
  errorKind: string;
  message: string;
};

/** Payload for {@link TURN_ENQUEUED_METHOD}. Must match `EnqueuedParams` in `src/protocol.rs`. */
export type EnqueuedParams = {
  turnId: string;
  seq: number;
  state: string;
};

/** Payload for {@link TURN_ACTIVATED_METHOD}. Must match `ActivatedParams` in `src/protocol.rs`. */
export type ActivatedParams = {
  turnId: string;
};

/** Payload for {@link TURN_SETTLED_METHOD}. Must match `SettledParams` in `src/protocol.rs`. */
export type SettledParams = {
  turnId: string;
  result: TurnResult;
};

/** Must match `TurnResult` in `src/protocol.rs`. */
export type TurnResult = {
  kind: string;
  text: string | null;
  finishReason: string | null;
  errorKind: string | null;
  message: string | null;
};

/**
 * Result for `kqode.git.status`: the formatted working-tree label (e.g.
 * `⎇ main*`), or `null` when the workspace is not a git repository or `git`
 * could not be queried. The Rust backend owns parsing and formatting
 * (`GitStatusResult` in `src/protocol.rs`); keep the two shapes in lockstep.
 */
export type GitStatusResult = {
  label: string | null;
};
