[workspace]
members = [
    "crates/kqode-cli",
    "crates/kqode-core",
    "crates/kqode-desktop",
    "crates/kqode-provider",
    "xtask",
]
default-members = ["crates/kqode-desktop"]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
rust-version = "1.94.0"
license = "MIT OR Apache-2.0"
