//! Append-only durable session-log truth for resumable conversations.
//!
//! The log stores one JSON object per line so later resume/reindex code can
//! rebuild session state without treating SQLite as the only source of truth.

use std::fs::{OpenOptions, create_dir_all};
use std::io::{BufWriter, Write};
use std::path::Path;

use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};

/// One append-only durable session-log event.
#[derive(Clone, Debug, Deserialize, Serialize, Eq, PartialEq)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum SessionLogEvent {
    SessionStarted {
        session_id: String,
        created_at_ms: i64,
        workspace_cwd: String,
        canonical_workspace_cwd: String,
    },
    TurnEnqueued {
        turn_id: String,
        seq: u64,
        prompt: String,
        at_ms: i64,
    },
    TurnSettled {
        turn_id: String,
        settled_kind: String,
        text: Option<String>,
        finish_reason: Option<String>,
        error_kind: Option<String>,
        message: Option<String>,
        at_ms: i64,
    },
    /// A compaction summary was produced, covering rounds up to
    /// `covered_through_seq` (inclusive). The latest such event wins on resume.
    Compacted {
        covered_through_seq: u64,
        summary: String,
        at_ms: i64,
    },
    /// A short session summary was generated by the hidden title summarizer for
    /// the resume list and terminal title. The latest such event wins on
    /// reindex, overriding the first-prompt-derived placeholder.
    SummaryGenerated { summary: String, at_ms: i64 },
}

/// Appends one durable event to `path`, creating the parent directory first.
///
/// # Errors
/// Returns an error when the directory cannot be created, the file cannot be
/// opened, or the JSON line cannot be written.
pub fn append_event(path: &Path, event: &SessionLogEvent) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        create_dir_all(parent)?;
    }
    let file = OpenOptions::new().create(true).append(true).open(path)?;
    let mut writer = BufWriter::new(file);
    serde_json::to_writer(&mut writer, event)?;
    writer.write_all(b"\n")?;
    writer.flush()
}

/// Malformed JSONL session-log line that is not a crash-truncated tail.
#[derive(Debug)]
pub struct SessionLogParseError {
    line: usize,
    source: serde_json::Error,
}

impl std::fmt::Display for SessionLogParseError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "line {} is not a valid session-log event: {}",
            self.line, self.source
        )
    }
}

impl std::error::Error for SessionLogParseError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        Some(&self.source)
    }
}

/// Parses JSONL session events, tolerating only a malformed unterminated tail.
///
/// A crash can leave the final append without a newline and with partial JSON.
/// That tail is ignored so the valid prefix remains resumable. Malformed lines
/// before the tail, or any malformed line in a newline-terminated file, still
/// fail closed because they indicate real corruption rather than an interrupted
/// append.
pub fn parse_jsonl_prefix<T: DeserializeOwned>(
    contents: &str,
) -> Result<Vec<T>, SessionLogParseError> {
    let lines = contents.lines().collect::<Vec<_>>();
    let final_line_may_be_truncated = !contents.is_empty() && !contents.ends_with('\n');
    let mut events = Vec::with_capacity(lines.len());
    for (index, line) in lines.iter().enumerate() {
        match serde_json::from_str::<T>(line) {
            Ok(event) => events.push(event),
            Err(_) if final_line_may_be_truncated && index + 1 == lines.len() => break,
            Err(source) => {
                return Err(SessionLogParseError {
                    line: index + 1,
                    source,
                });
            }
        }
    }
    Ok(events)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_jsonl_prefix_ignores_a_truncated_tail() {
        let first = serde_json::to_string(&SessionLogEvent::SessionStarted {
            session_id: "sess".to_owned(),
            created_at_ms: 1,
            workspace_cwd: "w".to_owned(),
            canonical_workspace_cwd: "w".to_owned(),
        })
        .unwrap();
        let events = parse_jsonl_prefix::<SessionLogEvent>(&format!("{first}\n{{\"kind\""))
            .expect("valid prefix");

        assert_eq!(events.len(), 1);
    }

    #[test]
    fn parse_jsonl_prefix_rejects_malformed_middle_lines() {
        let first = serde_json::to_string(&SessionLogEvent::SessionStarted {
            session_id: "sess".to_owned(),
            created_at_ms: 1,
            workspace_cwd: "w".to_owned(),
            canonical_workspace_cwd: "w".to_owned(),
        })
        .unwrap();
        let error =
            parse_jsonl_prefix::<SessionLogEvent>(&format!("{first}\nnot-json\n{{")).unwrap_err();

        assert_eq!(error.line, 2);
    }
}
