use serde::{Deserialize, Serialize};

mod providers;
pub use providers::*;

/// Hidden argument that starts the internal JSON-RPC backend loop.
pub const BACKEND_MODE_ARG: &str = "--__kqode-json-rpc-backend";

/// JSON-RPC notification the backend emits exactly once, immediately after its
/// stdio transport is live and before it handles any request.
///
/// It signals "I am listening and speaking JSON-RPC," so a client can bound
/// startup readiness on this notification instead of the OS process-spawn event
/// (a backend that spawns but never speaks would otherwise slip past the startup
/// timeout). The mirrored TypeScript constant lives in
/// `tui/src/contracts/backend/messages.ts` (`BACKEND_READY_METHOD`).
pub const BACKEND_READY_METHOD: &str = "kqode.backend.ready";

/// Server→client notification carrying one chunk of streamed assistant text.
/// Mirrored in `tui/src/contracts/backend/messages.ts`.
pub const TOKEN_DELTA_METHOD: &str = "kqode/tokenDelta";

/// Server→client notification marking the natural end of a streamed turn.
/// Mirrored in `tui/src/contracts/backend/messages.ts`.
pub const TURN_END_METHOD: &str = "kqode/turnEnd";

/// Server→client notification for a turn that ended with a provider/network
/// error. Mirrored in `tui/src/contracts/backend/messages.ts`.
pub const TURN_ERROR_METHOD: &str = "kqode/turnError";

/// `status` value when a submit is accepted and streaming has begun.
pub const SUBMIT_STATUS_STREAMING: &str = "streaming";

/// `status` value when a submit cannot run because no API key is configured.
pub const SUBMIT_STATUS_NEEDS_CONFIGURATION: &str = "needsConfiguration";

/// JSON-RPC code for method lookup failures.
pub const JSON_RPC_METHOD_NOT_FOUND: i32 = -32601;

/// JSON-RPC code for requests whose params do not match the method contract.
pub const JSON_RPC_INVALID_PARAMS: i32 = -32602;

/// KQode-owned JSON-RPC methods supported by this slice.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RpcMethod {
    MessageSubmit,
    GitStatus,
    ProviderList,
    SelectionGet,
    SelectionSet,
    ProviderClearKey,
    ProviderSetKey,
    ProviderModels,
}

impl RpcMethod {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::MessageSubmit => "kqode.message.submit",
            Self::GitStatus => "kqode.git.status",
            Self::ProviderList => PROVIDER_LIST_METHOD,
            Self::SelectionGet => SELECTION_GET_METHOD,
            Self::SelectionSet => SELECTION_SET_METHOD,
            Self::ProviderClearKey => PROVIDER_CLEAR_KEY_METHOD,
            Self::ProviderSetKey => PROVIDER_SET_KEY_METHOD,
            Self::ProviderModels => PROVIDER_MODELS_METHOD,
        }
    }

    /// Resolves a wire method name to its [`RpcMethod`], or `None` when the
    /// backend does not implement it (yielding a method-not-found response).
    #[must_use]
    pub fn from_method(method: &str) -> Option<Self> {
        [
            Self::MessageSubmit,
            Self::GitStatus,
            Self::ProviderList,
            Self::SelectionGet,
            Self::SelectionSet,
            Self::ProviderClearKey,
            Self::ProviderSetKey,
            Self::ProviderModels,
        ]
        .into_iter()
        .find(|candidate| candidate.as_str() == method)
    }
}

/// Params for `kqode.message.submit`.
///
/// `turnId` is generated by the client so it can register notification handlers
/// before sending, correlating streamed events without depending on ack
/// ordering. Kept in lockstep with the TypeScript `MessageSubmitParams`.
#[derive(Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct MessageSubmitParams {
    pub text: String,
    pub turn_id: String,
}

/// Result for `kqode.message.submit`: an immediate streaming ack.
///
/// `status` is one of [`SUBMIT_STATUS_STREAMING`] or
/// [`SUBMIT_STATUS_NEEDS_CONFIGURATION`]; `turnId` echoes the client's id.
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MessageSubmitResult {
    pub turn_id: String,
    pub status: &'static str,
}

/// Payload for [`BACKEND_READY_METHOD`].
///
/// Carries the backend-minted session id so the client can scope its own
/// per-session log to the same session. Kept in lockstep with the TypeScript
/// `BackendReadyParams`.
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct BackendReadyParams {
    pub session_id: String,
}

/// Payload for [`TOKEN_DELTA_METHOD`].
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TokenDeltaParams {
    pub turn_id: String,
    pub delta: String,
}

/// Payload for [`TURN_END_METHOD`].
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnEndParams {
    pub turn_id: String,
    pub finish_reason: Option<String>,
}

/// Payload for [`TURN_ERROR_METHOD`].
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TurnErrorParams {
    pub turn_id: String,
    pub error_kind: String,
    pub message: String,
}

/// Result for `kqode.git.status`: the formatted working-tree label, or `null`
/// when the workspace is not a git repository (or `git` could not be queried).
/// The backend owns parsing and formatting; the client renders `label` verbatim.
/// Kept in lockstep with the TypeScript `GitStatusResult`.
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GitStatusResult {
    pub label: Option<String>,
}
