'use strict';

// Pure builder for the KQode Homebrew formula. No fs/network so the Ruby output
// stays trivially testable. The publish workflow feeds it the version and the
// per-archive SHA-256 values parsed from the GitHub Release `checksums.txt`.

const DESC = 'Rust-core coding-agent harness with a TypeScript Ink terminal UI';
const HOMEPAGE = 'https://github.com/kefeiqian/kqode-cli';
const LICENSE = 'MIT OR Apache-2.0';
const RELEASE_BASE = 'https://github.com/kefeiqian/kqode-cli/releases/download';

// Homebrew ships only the POSIX standalone executables. Intel macOS is not built
// (Apple Silicon only) and Windows is served by winget, so neither appears here.
// Each entry maps a Homebrew platform guard (`on_<os>` + `on_<cpu>`) to its
// GitHub Release archive.
const FORMULA_TARGETS = [
  { os: 'macos', cpu: 'arm', archive: 'kqode-darwin-arm64.tar.gz' },
  { os: 'linux', cpu: 'arm', archive: 'kqode-linux-arm64.tar.gz' },
  { os: 'linux', cpu: 'intel', archive: 'kqode-linux-x64.tar.gz' }
];

/** Renders one `on_<cpu>` block with the archive URL and pinned checksum. */
function archBlock(target, version, checksums) {
  const sha = checksums[target.archive];
  if (!sha) {
    throw new Error(`missing checksum for ${target.archive}`);
  }
  const url = `${RELEASE_BASE}/v${version}/${target.archive}`;
  return [
    `    on_${target.cpu} do`,
    `      url "${url}"`,
    `      sha256 "${sha}"`,
    '    end'
  ].join('\n');
}

/** Groups the targets by OS, preserving the {@link FORMULA_TARGETS} order. */
function groupByOs(targets) {
  const byOs = new Map();
  for (const target of targets) {
    if (!byOs.has(target.os)) byOs.set(target.os, []);
    byOs.get(target.os).push(target);
  }
  return byOs;
}

/**
 * Renders the complete `Formula/kqode.rb` Ruby source for `version`.
 *
 * `checksums` maps each release archive file name to its lowercase SHA-256.
 *
 * # Errors
 *
 * Throws when any archive required by {@link FORMULA_TARGETS} has no checksum,
 * so a partial release can never yield a formula that installs an unverified
 * binary.
 */
function renderFormula({ version, checksums }) {
  if (!version) {
    throw new Error('renderFormula requires a version');
  }
  const platformBlocks = [...groupByOs(FORMULA_TARGETS).entries()]
    .map(([os, targets]) => {
      const inner = targets.map((target) => archBlock(target, version, checksums)).join('\n');
      return `  on_${os} do\n${inner}\n  end`;
    })
    .join('\n\n');

  return [
    '# Generated by packaging/homebrew/generate-formula.cjs — do not edit by hand.',
    'class Kqode < Formula',
    `  desc "${DESC}"`,
    `  homepage "${HOMEPAGE}"`,
    `  version "${version}"`,
    `  license "${LICENSE}"`,
    '',
    platformBlocks,
    '',
    '  def install',
    '    bin.install "kqode"',
    '  end',
    '',
    '  test do',
    '    system bin/"kqode", "--version"',
    '  end',
    'end',
    ''
  ].join('\n');
}

module.exports = { renderFormula, FORMULA_TARGETS, DESC, HOMEPAGE, LICENSE, RELEASE_BASE };
